var searchData=
[
  ['callable_5ftype_0',['callable_type',['../group__util.html#gaaff949a6c33139e76654e2d68a81c34e',1,'argon::action::util']]],
  ['called_20after_20parsing_20an_20argument_20s_20value_1',['8. value actions - Functions that are called after parsing an argument&apos;s value.',['../md_docs_2tutorial.html#autotoc_md8-value-actions---functions-that-are-called-after-parsing-an-arguments-value',1,'']]],
  ['called_20immediately_20after_20parsing_20an_20argument_20s_20flag_2',['1. on-flag actions - Functions that are called immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md1-on-flag-actions---functions-that-are-called-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['check_5ffile_5fexists_3',['check_file_exists',['../namespaceargon_1_1action.html#a702926ab34e1578b97eca800f0cb0d6d',1,'argon::action']]],
  ['checks_4',['Suppressing Argument Group Checks',['../md_docs_2tutorial.html#suppressing-argument-group-checks',1,'']]],
  ['checks_20for_20other_20arguments_5',['4. &lt;tt&gt;suppress_arg_checks&lt;/tt&gt; - Using a suppressing argument results in suppressing requirement checks for other arguments.',['../md_docs_2tutorial.html#autotoc_md4-suppress_arg_checks---using-a-suppressing-argument-results-in-suppressing-requirement-checks-for-other-arguments',1,'']]],
  ['choices_6',['choices',['../classargon_1_1argument.html#afe77788f38d77a6eee7a0c1808027468',1,'argon::argument::choices(const CR &amp;choices) noexcept'],['../classargon_1_1argument.html#a7bc0d608998b720a9b126c8449ce9dfa',1,'argon::argument::choices(std::initializer_list&lt; value_type &gt; choices) noexcept'],['../classargon_1_1argument.html#af1380264290c4b894c58e589ac3add60',1,'argon::argument::choices(const std::convertible_to&lt; value_type &gt; auto &amp;... choices) noexcept']]],
  ['choices_20tt_20a_20list_20of_20valid_20argument_20values_7',['7. &lt;tt&gt;choices&lt;/tt&gt; - A list of valid argument values.',['../md_docs_2tutorial.html#autotoc_md7-choices---a-list-of-valid-argument-values',1,'']]],
  ['class_8',['The Parser Class',['../md_docs_2tutorial.html#the-parser-class',1,'']]],
  ['class_20instance_9',['1. &lt;tt&gt;help&lt;/tt&gt; - The argument&apos;s description which will be printed when printing the parser class instance.',['../md_docs_2tutorial.html#autotoc_md1-help---the-arguments-description-which-will-be-printed-when-printing-the-parser-class-instance',1,'']]],
  ['cmake_20integration_10',['CMake Integration',['../md_docs_2tutorial.html#cmake-integration',1,'']]],
  ['command_20line_11',['2. &lt;tt&gt;implicit_values&lt;/tt&gt; - A list of values which will be set for an argument if only its flag but no values are parsed from the command-line.',['../md_docs_2tutorial.html#autotoc_md2-implicit_values---a-list-of-values-which-will-be-set-for-an-argument-if-only-its-flag-but-no-values-are-parsed-from-the-command-line',1,'']]],
  ['command_20line_20an_20exception_20will_20be_20thrown_12',['3. &lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#autotoc_md3-required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['command_20line_20values_20until_20it_20s_20upper_20nargs_20bound_20is_20reached_13',['6. &lt;tt&gt;greedy&lt;/tt&gt; - If this option is set, the argument will consume ALL command-line values until it&apos;s upper nargs bound is reached.',['../md_docs_2tutorial.html#autotoc_md6-greedy---if-this-option-is-set-the-argument-will-consume-all-command-line-values-until-its-upper-nargs-bound-is-reached',1,'']]],
  ['common_20parameters_14',['Common Parameters',['../md_docs_2tutorial.html#common-parameters',1,'']]],
  ['common_20utility_15',['Common Utility',['../md_docs_2tutorial.html#common-utility',1,'']]],
  ['compatibilty_16',['Compiler Compatibilty',['../index.html#compiler-compatibilty',1,'']]],
  ['compiler_20compatibilty_17',['Compiler Compatibilty',['../index.html#compiler-compatibilty',1,'']]],
  ['complete_20example_18',['Complete Example',['../md_docs_2tutorial.html#complete-example',1,'']]],
  ['compound_20arguments_19',['Compound Arguments',['../md_docs_2tutorial.html#compound-arguments',1,'']]],
  ['concepts_2ehpp_20',['concepts.hpp',['../util_2concepts_8hpp.html',1,'(Global Namespace)'],['../action_2util_2concepts_8hpp.html',1,'(Global Namespace)']]],
  ['consume_20all_20command_20line_20values_20until_20it_20s_20upper_20nargs_20bound_20is_20reached_21',['6. &lt;tt&gt;greedy&lt;/tt&gt; - If this option is set, the argument will consume ALL command-line values until it&apos;s upper nargs bound is reached.',['../md_docs_2tutorial.html#autotoc_md6-greedy---if-this-option-is-set-the-argument-will-consume-all-command-line-values-until-its-upper-nargs-bound-is-reached',1,'']]],
  ['consume_20free_20values_22',['3. Positional arguments consume free values',['../md_docs_2tutorial.html#autotoc_md3-positional-arguments-consume-free-values',1,'']]],
  ['contains_5fwhitespaces_23',['contains_whitespaces',['../namespaceargon_1_1util.html#aba846525fe3d0d1b7f9e4720676a7f32',1,'argon::util']]],
  ['convertible_24',['convertible',['../group__util.html#gga3e4aa0f151992688a7a5e48dcc491340ae0a23947029316880c29e8533d8662a3',1,'argon::util']]],
  ['count_25',['count',['../classargon_1_1argument.html#a943c705b8e4fd22d4a790ed7bc089954',1,'argon::argument::count()'],['../classargon_1_1argument__parser.html#acf08a506d937f8c5ac7b8bcb721d2596',1,'argon::argument_parser::count()'],['../classargon_1_1detail_1_1argument__base.html#ac267c8cab20d3ebffbd8446fddaf3978',1,'argon::detail::argument_base::count()']]],
  ['count_5ftype_26',['count_type',['../namespaceargon_1_1nargs.html#ab775fbb2851d477537b40f4441265265',1,'argon::nargs::count_type'],['../classargon_1_1argument.html#a5c2b2b3ab6c0df23f9880edb63c0dc96',1,'argon::argument::count_type']]],
  ['cpp_20argon_27',['cpp argon',['../index.html',1,'CPP-ARGON'],['../md_docs_2tutorial.html#setting-up-cpp-argon',1,'Setting Up CPP-ARGON']]],
  ['create_28',['create',['../classargon_1_1argument__group.html#aab8ce06b64824fbf98ec0190026a6462',1,'argon::argument_group']]],
  ['creating_20new_20groups_29',['Creating New Groups',['../md_docs_2tutorial.html#creating-new-groups',1,'']]],
  ['creating_20subparsers_30',['Creating Subparsers',['../md_docs_2tutorial.html#creating-subparsers',1,'']]],
  ['curr_5farg_31',['curr_arg',['../structargon_1_1argument__parser_1_1parsing__state.html#a05ad36855bb055024b13e0e856caa5fa',1,'argon::argument_parser::parsing_state']]],
  ['curr_5fpos_5farg_5fit_32',['curr_pos_arg_it',['../structargon_1_1argument__parser_1_1parsing__state.html#aa5e0c3e9555b2d59b3b0ffeecd2032a7',1,'argon::argument_parser::parsing_state']]]
];
