var searchData=
[
  ['s_20description_20which_20will_20be_20printed_20when_20printing_20the_20parser_20class_20instance_0',['1. &lt;tt&gt;help&lt;/tt&gt; - The argument&apos;s description which will be printed when printing the parser class instance.',['../md_docs_2tutorial.html#autotoc_md1-help---the-arguments-description-which-will-be-printed-when-printing-the-parser-class-instance',1,'']]],
  ['s_20flag_1',['6. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md6-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['s_20flag_20is_20parsed_20from_20the_20command_20line_20but_20no_20values_20follow_2',['5. &lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#autotoc_md5-implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['s_20value_3',['3. Value actions - Function performed after parsing an argument&apos;s value.',['../md_docs_2tutorial.html#autotoc_md3-value-actions---function-performed-after-parsing-an-arguments-value',1,'']]],
  ['s_20value_20is_20not_20passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_4',['1. &lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#autotoc_md1-required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['s_20value_20will_20overrite_20the_20tt_20required_20tt_20option_20for_20other_20optional_20arguments_20and_20all_20positional_20arguments_5',['2. &lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, parsing it&apos;s value will overrite the &lt;tt&gt;required&lt;/tt&gt; option for other optional arguments and all positional arguments.',['../md_docs_2tutorial.html#autotoc_md2-bypass_required---if-this-option-is-set-for-an-argument-parsing-its-value-will-overrite-the-required-option-for-other-optional-arguments-and-all-positional-arguments',1,'']]],
  ['same_6',['same',['../concepts_8hpp.html#a26fa93551a0b7be6a2435645a1ea4cafa51037a4a37730f52c8732586d3aaa316',1,'ap::detail']]],
  ['secondary_7',['secondary',['../structap_1_1detail_1_1argument__name.html#a5f48a3d6c61206fb5ad417ce221adfb0',1,'ap::detail::argument_name']]],
  ['set_20as_20a_3a_8',['3. &lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#autotoc_md3-nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['set_20for_20an_20argument_20and_20it_20s_20value_20is_20not_20passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_9',['1. &lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#autotoc_md1-required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['set_20for_20an_20argument_20if_20only_20it_20s_20flag_20is_20parsed_20from_20the_20command_20line_20but_20no_20values_20follow_10',['5. &lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#autotoc_md5-implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['set_20for_20an_20argument_20parsing_20it_20s_20value_20will_20overrite_20the_20tt_20required_20tt_20option_20for_20other_20optional_20arguments_20and_20all_20positional_20arguments_11',['2. &lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, parsing it&apos;s value will overrite the &lt;tt&gt;required&lt;/tt&gt; option for other optional arguments and all positional arguments.',['../md_docs_2tutorial.html#autotoc_md2-bypass_required---if-this-option-is-set-for-an-argument-parsing-its-value-will-overrite-the-required-option-for-other-optional-arguments-and-all-positional-arguments',1,'']]],
  ['set_5fvalue_12',['set_value',['../classap_1_1detail_1_1argument__base.html#a4ec0c0a188f869f8be1e04663dd42ede',1,'ap::detail::argument_base']]],
  ['sets_20the_20allowed_20number_20of_20values_20to_20be_20parsed_20for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_13',['3. &lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#autotoc_md3-nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['setting_20up_20cpp_20ap_14',['Setting Up CPP-AP',['../md_docs_2tutorial.html#setting-up-cpp-ap',1,'']]],
  ['specific_20for_20optional_20arguments_15',['Parameters Specific for Optional Arguments',['../md_docs_2tutorial.html#parameters-specific-for-optional-arguments',1,'']]],
  ['specifiers_2ehpp_16',['specifiers.hpp',['../specifiers_8hpp.html',1,'']]],
  ['specify_20on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_17',['6. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md6-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['str_18',['str',['../structap_1_1detail_1_1argument__name.html#a3b1c696b69aa8c6842e4411ca44b8424',1,'ap::detail::argument_name']]],
  ['str_5futility_2ehpp_19',['str_utility.hpp',['../str__utility_8hpp.html',1,'']]]
];
