var searchData=
[
  ['valid_20argument_20values_0',['&lt;tt&gt;choices&lt;/tt&gt; - A list of valid argument values.',['../md_docs_2tutorial.html#choices---a-list-of-valid-argument-values',1,'']]],
  ['value_1',['value',['../structap_1_1action_1_1detail_1_1apply__visitor.html#a9e28c99a481bd6fcfb83a294184db21d',1,'ap::action::detail::apply_visitor::value'],['../classap_1_1argument__parser.html#a5a51e8b54c96d6bddbeabd9bc4ff7cb7',1,'ap::argument_parser::value()'],['../classap_1_1detail_1_1argument__base.html#a66137a69a06d000e2b7a677a28f6b842',1,'ap::detail::argument_base::value()'],['../md_docs_2tutorial.html#value-actions---function-performed-after-parsing-an-arguments-value',1,'Value actions - Function performed after parsing an argument&apos;s value.']]],
  ['value_20actions_20function_20performed_20after_20parsing_20an_20argument_20s_20value_2',['Value actions - Function performed after parsing an argument&apos;s value.',['../md_docs_2tutorial.html#value-actions---function-performed-after-parsing-an-arguments-value',1,'']]],
  ['value_20actions_20you_20can_20specify_20on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_3',['On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['value_20for_20an_20argument_20which_20will_20be_20used_20if_20no_20values_20for_20this_20argument_20are_20parsed_4',['&lt;tt&gt;default_value&lt;/tt&gt; - The default value for an argument which will be used if no values for this argument are parsed',['../md_docs_2tutorial.html#default_value---the-default-value-for-an-argument-which-will-be-used-if-no-values-for-this-argument-are-parsed',1,'']]],
  ['value_20is_20not_20passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_5',['&lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['value_20type_3a_20a_20href_20https_3a_20en_20cppreference_20com_20w_20cpp_20types_20is_5farithmetic_20arithmetic_20a_6',['value type: a href https: en cppreference com w cpp types is_arithmetic arithmetic a',['../md_docs_2tutorial.html#geq--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;geq&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#gt--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;gt&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#leq--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;leq&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#lt--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;lt&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#within--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;within&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)']]],
  ['value_20type_3a_20tt_20std_3a_3astring_20tt_7',['&lt;tt&gt;check_file_exists&lt;/tt&gt; | observe (value type: &lt;tt&gt;std::string&lt;/tt&gt;)',['../md_docs_2tutorial.html#check_file_exists--observe-value-type-stdstring',1,'']]],
  ['value_20which_20will_20be_20set_20for_20an_20argument_20if_20only_20it_20s_20flag_20is_20parsed_20from_20the_20command_20line_20but_20no_20values_20follow_8',['&lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['value_20will_20overrite_20the_20tt_20required_20tt_20option_20for_20other_20optional_20arguments_20and_20all_20positional_20arguments_9',['&lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, parsing it&apos;s value will overrite the &lt;tt&gt;required&lt;/tt&gt; option for other optional arguments and all positional arguments.',['../md_docs_2tutorial.html#bypass_required---if-this-option-is-set-for-an-argument-parsing-its-value-will-overrite-the-required-option-for-other-optional-arguments-and-all-positional-arguments',1,'']]],
  ['value_5faction_5fvariant_5ftype_10',['value_action_variant_type',['../utility_8hpp.html#aa90d2a5ef295ac93ed6d16026869b8bf',1,'ap::action::detail']]],
  ['value_5falready_5fset_11',['value_already_set',['../classap_1_1error_1_1value__already__set.html',1,'ap::error::value_already_set'],['../classap_1_1error_1_1value__already__set.html#ac82a31c8f9af27c50ed837dd0446ca48',1,'ap::error::value_already_set::value_already_set()']]],
  ['value_5for_12',['value_or',['../classap_1_1argument__parser.html#ad2da93974b1e272fb54aa8fb6cc93e21',1,'ap::argument_parser']]],
  ['value_5ftype_13',['value_type',['../classap_1_1argument_1_1optional.html#a8c76a8de1c750908e54f1e49a1ab00c0',1,'ap::argument::optional::value_type'],['../classap_1_1argument_1_1positional.html#a8d79c650f1a11157b93b2ee5b25257de',1,'ap::argument::positional::value_type']]],
  ['values_14',['values',['../md_docs_2tutorial.html#choices---a-list-of-valid-argument-values',1,'&lt;tt&gt;choices&lt;/tt&gt; - A list of valid argument values.'],['../md_docs_2tutorial.html#predefined-parameter-values',1,'Predefined Parameter Values'],['../md_docs_2tutorial.html#retrieving-argument-values',1,'Retrieving Argument Values'],['../classap_1_1detail_1_1argument__base.html#abbcc2eaf1cfc00f1aaf62208d1a99d95',1,'ap::detail::argument_base::values()'],['../classap_1_1argument__parser.html#a80270803f7f3c59c3aeac9f6d33205ce',1,'ap::argument_parser::values()']]],
  ['values_20follow_15',['&lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['values_20for_20this_20argument_20are_20parsed_16',['&lt;tt&gt;default_value&lt;/tt&gt; - The default value for an argument which will be used if no values for this argument are parsed',['../md_docs_2tutorial.html#default_value---the-default-value-for-an-argument-which-will-be-used-if-no-values-for-this-argument-are-parsed',1,'']]],
  ['values_20to_20be_20parsed_20for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_17',['&lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['verbose_18',['verbose',['../classap_1_1argument__parser.html#aa0e0f6e7fff9878c25f8453eab99bd5a',1,'ap::argument_parser']]]
];
