var searchData=
[
  ['name_0',['name',['../classap_1_1detail_1_1argument__interface.html#a7c90599cd7a06c20e94e4ed95afbec69',1,'ap::detail::argument_interface']]],
  ['nargs_1',['nargs',['../classap_1_1argument_1_1optional.html#a68fdb47e70fee66c58e9bdaceeb66ec8',1,'ap::argument::optional::nargs(const ap::nargs::range &amp;range) noexcept'],['../classap_1_1argument_1_1optional.html#a9221e6e6e0456b28bfbeeff0264630e0',1,'ap::argument::optional::nargs(const count_type count) noexcept'],['../classap_1_1argument_1_1optional.html#ae845c5854ac0515d75f9c6b4c3dbed91',1,'ap::argument::optional::nargs(const count_type nlow, const count_type nhigh) noexcept']]],
  ['nargs_20tt_20sets_20the_20allowed_20number_20of_20values_20to_20be_20parsed_20for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_2',['&lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['no_20values_20follow_3',['&lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['no_20values_20for_20this_20argument_20are_20parsed_4',['&lt;tt&gt;default_value&lt;/tt&gt; - The default value for an argument which will be used if no values for this argument are parsed',['../md_docs_2tutorial.html#default_value---the-default-value-for-an-argument-which-will-be-used-if-no-values-for-this-argument-are-parsed',1,'']]],
  ['not_20passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_5',['&lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['notes_6',['Dev Notes',['../md_docs_2dev__notes.html',1,'']]],
  ['number_20of_20values_20to_20be_20parsed_20for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_7',['&lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['nused_8',['nused',['../classap_1_1detail_1_1argument__interface.html#a5ebb0ab17b0878f8395ac0fb00cea6c3',1,'ap::detail::argument_interface']]],
  ['nvalues_5fin_5frange_9',['nvalues_in_range',['../classap_1_1detail_1_1argument__interface.html#abb4c6a08b8ff8383cd5800195f0055f8',1,'ap::detail::argument_interface']]]
];
