var searchData=
[
  ['observe_0',['observe',['../structap_1_1action__type_1_1observe.html',1,'ap::action_type']]],
  ['of_20valid_20argument_20values_1',['2. &lt;tt&gt;choices&lt;/tt&gt; - A list of valid argument values.',['../md_docs_2tutorial.html#autotoc_md2-choices---a-list-of-valid-argument-values',1,'']]],
  ['of_20values_20to_20be_20parsed_20for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_2',['3. &lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#autotoc_md3-nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['on_20flag_20actions_20for_20optional_20arguments_20apart_20from_20value_20actions_20you_20can_20specify_20on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_3',['6. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md6-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_4',['6. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md6-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['on_5fflag_5',['on_flag',['../structap_1_1action__type_1_1on__flag.html',1,'ap::action_type']]],
  ['only_20it_20s_20flag_20is_20parsed_20from_20the_20command_20line_20but_20no_20values_20follow_6',['5. &lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#autotoc_md5-implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['operator_28_29_7',['operator()',['../structap_1_1action_1_1detail_1_1apply__visitor.html#ab69a7d04a929edb91971a0f8bb13c8e0',1,'ap::action::detail::apply_visitor::operator()(const callable_type&lt; action_type::modify, value_type &gt; &amp;action) const'],['../structap_1_1action_1_1detail_1_1apply__visitor.html#aaea88f00455d1288c3c9f6e8ec017dba',1,'ap::action::detail::apply_visitor::operator()(const callable_type&lt; action_type::observe, value_type &gt; &amp;action) const'],['../structap_1_1action_1_1detail_1_1apply__visitor.html#af95e9cfea97e4517ac970db795ec8ddd',1,'ap::action::detail::apply_visitor::operator()(const callable_type&lt; action_type::transform, value_type &gt; &amp;action) const']]],
  ['operator_3c_3c_8',['operator&lt;&lt;',['../classap_1_1argument__parser.html#aeae32e2a82ba92d715da825b1086ced8',1,'ap::argument_parser::operator&lt;&lt;'],['../predefined__actions_8hpp.html#ac965b62b8fd497f0cdf32b1bd14d13e3',1,'ap::operator&lt;&lt;()'],['../structap_1_1detail_1_1argument__name.html#af67eccd32b26b5db123ce8e90602ef83',1,'ap::detail::argument_name::operator&lt;&lt;']]],
  ['operator_3d_3d_9',['operator==',['../structap_1_1detail_1_1argument__token.html#a93bb5224c1238c99ee0d758b2599961d',1,'ap::detail::argument_token::operator==()'],['../structap_1_1detail_1_1argument__name.html#a39c467231e068be443da283c1ba7b836',1,'ap::detail::argument_name::operator==()'],['../classap_1_1argument_1_1optional.html#ad28df00f93976566fa35777df9f8d892',1,'ap::argument::optional::operator==()'],['../classap_1_1argument_1_1positional.html#a2dd36fe1f755c75e2671f69793afa15e',1,'ap::argument::positional::operator==()']]],
  ['option_20is_20set_20for_20an_20argument_20and_20it_20s_20value_20is_20not_20passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_10',['1. &lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#autotoc_md1-required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['option_20is_20set_20for_20an_20argument_20parsing_20it_20s_20value_20will_20overrite_20the_20tt_20required_20tt_20option_20for_20other_20optional_20arguments_20and_20all_20positional_20arguments_11',['2. &lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, parsing it&apos;s value will overrite the &lt;tt&gt;required&lt;/tt&gt; option for other optional arguments and all positional arguments.',['../md_docs_2tutorial.html#autotoc_md2-bypass_required---if-this-option-is-set-for-an-argument-parsing-its-value-will-overrite-the-required-option-for-other-optional-arguments-and-all-positional-arguments',1,'']]],
  ['optional_12',['optional',['../classap_1_1argument_1_1optional.html',1,'ap::argument::optional&lt; T &gt;'],['../classap_1_1argument_1_1optional.html#a2780f28dfc412c48e4e2162e732cf40f',1,'ap::argument::optional::optional()']]],
  ['optional_20arguments_13',['Parameters Specific for Optional Arguments',['../md_docs_2tutorial.html#parameters-specific-for-optional-arguments',1,'']]],
  ['optional_20arguments_20and_20all_20positional_20arguments_14',['2. &lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, parsing it&apos;s value will overrite the &lt;tt&gt;required&lt;/tt&gt; option for other optional arguments and all positional arguments.',['../md_docs_2tutorial.html#autotoc_md2-bypass_required---if-this-option-is-set-for-an-argument-parsing-its-value-will-overrite-the-required-option-for-other-optional-arguments-and-all-positional-arguments',1,'']]],
  ['optional_20arguments_20apart_20from_20value_20actions_20you_20can_20specify_20on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_15',['6. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md6-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['optional_2ehpp_16',['optional.hpp',['../optional_8hpp.html',1,'']]],
  ['ordering_17',['ordering',['../classap_1_1nargs_1_1range.html#a995cfe8b423e49a6618976404716337d',1,'ap::nargs::range']]],
  ['other_20optional_20arguments_20and_20all_20positional_20arguments_18',['2. &lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, parsing it&apos;s value will overrite the &lt;tt&gt;required&lt;/tt&gt; option for other optional arguments and all positional arguments.',['../md_docs_2tutorial.html#autotoc_md2-bypass_required---if-this-option-is-set-for-an-argument-parsing-its-value-will-overrite-the-required-option-for-other-optional-arguments-and-all-positional-arguments',1,'']]],
  ['overrite_20the_20tt_20required_20tt_20option_20for_20other_20optional_20arguments_20and_20all_20positional_20arguments_19',['2. &lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, parsing it&apos;s value will overrite the &lt;tt&gt;required&lt;/tt&gt; option for other optional arguments and all positional arguments.',['../md_docs_2tutorial.html#autotoc_md2-bypass_required---if-this-option-is-set-for-an-argument-parsing-its-value-will-overrite-the-required-option-for-other-optional-arguments-and-all-positional-arguments',1,'']]],
  ['overview_20',['Overview',['../index.html#overview',1,'']]]
];
