var searchData=
[
  ['en_20cppreference_20com_20w_20cpp_20types_20is_5farithmetic_20arithmetic_20a_0',['en cppreference com w cpp types is_arithmetic arithmetic a',['../md_docs_2tutorial.html#geq--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;geq&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#gt--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;gt&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#leq--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;leq&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#lt--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;lt&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)'],['../md_docs_2tutorial.html#within--observe-value-type-arithmetichttpsencppreferencecomwcpptypesis_arithmetic',1,'&lt;tt&gt;within&lt;/tt&gt; | observe (value type: &lt;a href=&quot;https://en.cppreference.com/w/cpp/types/is_arithmetic&quot; &gt;arithmetic&lt;/a&gt;)']]],
  ['examples_1',['Examples',['../md_docs_2tutorial.html#examples',1,'']]],
  ['exception_20will_20be_20thrown_2',['&lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['exceptions_2ehpp_3',['exceptions.hpp',['../exceptions_8hpp.html',1,'']]],
  ['executable_4',['Build the testing executable',['../md_docs_2dev__notes.html#build-the-testing-executable',1,'']]],
  ['executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_5',['On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]]
];
