var searchData=
[
  ['flag_20actions_20for_20optional_20arguments_20apart_20from_20value_20actions_20you_20can_20specify_20on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_0',['4. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md4-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['flag_20is_20parsed_20from_20the_20command_20line_20but_20no_20values_20follow_1',['2. &lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#autotoc_md2-implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['flag_5fchar_2',['flag_char',['../structap_1_1detail_1_1argument__name.html#a2fed035abf1d7553f5e47857b78abcd7',1,'ap::detail::argument_name']]],
  ['follow_3',['2. &lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#autotoc_md2-implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['for_20an_20argument_20and_20it_20s_20value_20is_20not_20passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_4',['2. &lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#autotoc_md2-required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['for_20an_20argument_20if_20only_20it_20s_20flag_20is_20parsed_20from_20the_20command_20line_20but_20no_20values_20follow_5',['2. &lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#autotoc_md2-implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['for_20an_20argument_20the_20tt_20required_20tt_20option_20for_20other_20arguments_20will_20be_20discarded_20if_20the_20bypassing_20argument_20is_20used_20in_20the_20command_20line_6',['3. &lt;tt&gt;bypass_required&lt;/tt&gt; - If this option is set for an argument, the &lt;tt&gt;required&lt;/tt&gt; option for other arguments will be discarded if the bypassing argument is used in the command-line.',['../md_docs_2tutorial.html#autotoc_md3-bypass_required---if-this-option-is-set-for-an-argument-the-required-option-for-other-arguments-will-be-discarded-if-the-bypassing-argument-is-used-in-the-command-line',1,'']]],
  ['for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_7',['1. &lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#autotoc_md1-nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['for_20an_20argument_20which_20will_20be_20used_20if_20no_20values_20for_20this_20argument_20are_20parsed_8',['4. &lt;tt&gt;default_value&lt;/tt&gt; - The default value for an argument which will be used if no values for this argument are parsed',['../md_docs_2tutorial.html#autotoc_md4-default_value---the-default-value-for-an-argument-which-will-be-used-if-no-values-for-this-argument-are-parsed',1,'']]],
  ['for_20optional_20arguments_9',['Parameters Specific for Optional Arguments',['../md_docs_2tutorial.html#parameters-specific-for-optional-arguments',1,'']]],
  ['for_20optional_20arguments_20apart_20from_20value_20actions_20you_20can_20specify_20on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_10',['4. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md4-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['formatting_11',['Formatting',['../md_docs_2dev__notes.html#formatting',1,'']]],
  ['from_20the_20command_20line_20but_20no_20values_20follow_12',['2. &lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#autotoc_md2-implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['from_20value_20actions_20you_20can_20specify_20on_20flag_20actions_20which_20are_20executed_20immediately_20after_20parsing_20an_20argument_20s_20flag_13',['4. On-flag actions - For optional arguments, apart from value actions, you can specify on-flag actions which are executed immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md4-on-flag-actions---for-optional-arguments-apart-from-value-actions-you-can-specify-on-flag-actions-which-are-executed-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['function_20performed_20after_20parsing_20an_20argument_20s_20value_14',['6. Value actions - Function performed after parsing an argument&apos;s value.',['../md_docs_2tutorial.html#autotoc_md6-value-actions---function-performed-after-parsing-an-arguments-value',1,'']]]
];
