var searchData=
[
  ['callable_5ftype_0',['callable_type',['../group__util.html#gabbe48ae9c9dbd3c12128353d76a3468f',1,'ap::action::util']]],
  ['called_20after_20parsing_20an_20argument_20s_20value_1',['8. value actions - Functions that are called after parsing an argument&apos;s value.',['../md_docs_2tutorial.html#autotoc_md8-value-actions---functions-that-are-called-after-parsing-an-arguments-value',1,'']]],
  ['called_20immediately_20after_20parsing_20an_20argument_20s_20flag_2',['1. on-flag actions - Functions that are called immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md1-on-flag-actions---functions-that-are-called-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['check_5ffile_5fexists_3',['check_file_exists',['../namespaceap_1_1action.html#a9d283d38ff65170085d0f95ad97a23cd',1,'ap::action']]],
  ['checks_4',['Suppressing Argument Group Checks',['../md_docs_2tutorial.html#suppressing-argument-group-checks',1,'']]],
  ['checks_20for_20other_20arguments_5',['4. &lt;tt&gt;suppress_arg_checks&lt;/tt&gt; - Using a suppressing argument results in suppressing requirement checks for other arguments.',['../md_docs_2tutorial.html#autotoc_md4-suppress_arg_checks---using-a-suppressing-argument-results-in-suppressing-requirement-checks-for-other-arguments',1,'']]],
  ['choices_6',['choices',['../classap_1_1argument.html#afddc2df8da7a693c30a46c4ca04e4433',1,'ap::argument::choices(const CR &amp;choices) noexcept'],['../classap_1_1argument.html#a9acd7f149c28df990606e8bb6685737a',1,'ap::argument::choices(std::initializer_list&lt; value_type &gt; choices) noexcept'],['../classap_1_1argument.html#a8ef6ceb9ae95c8c1454b8607b463c721',1,'ap::argument::choices(const std::convertible_to&lt; value_type &gt; auto &amp;... choices) noexcept']]],
  ['choices_20tt_20a_20list_20of_20valid_20argument_20values_7',['7. &lt;tt&gt;choices&lt;/tt&gt; - A list of valid argument values.',['../md_docs_2tutorial.html#autotoc_md7-choices---a-list-of-valid-argument-values',1,'']]],
  ['class_8',['The Parser Class',['../md_docs_2tutorial.html#the-parser-class',1,'']]],
  ['class_20instance_9',['1. &lt;tt&gt;help&lt;/tt&gt; - The argument&apos;s description which will be printed when printing the parser class instance.',['../md_docs_2tutorial.html#autotoc_md1-help---the-arguments-description-which-will-be-printed-when-printing-the-parser-class-instance',1,'']]],
  ['cmake_20integration_10',['CMake Integration',['../md_docs_2tutorial.html#cmake-integration',1,'']]],
  ['command_20line_11',['2. &lt;tt&gt;implicit_values&lt;/tt&gt; - A list of values which will be set for an argument if only its flag but no values are parsed from the command-line.',['../md_docs_2tutorial.html#autotoc_md2-implicit_values---a-list-of-values-which-will-be-set-for-an-argument-if-only-its-flag-but-no-values-are-parsed-from-the-command-line',1,'']]],
  ['command_20line_20an_20exception_20will_20be_20thrown_12',['3. &lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#autotoc_md3-required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['command_20line_20values_20until_20it_20s_20upper_20nargs_20bound_20is_20reached_13',['6. &lt;tt&gt;greedy&lt;/tt&gt; - If this option is set, the argument will consume ALL command-line values until it&apos;s upper nargs bound is reached.',['../md_docs_2tutorial.html#autotoc_md6-greedy---if-this-option-is-set-the-argument-will-consume-all-command-line-values-until-its-upper-nargs-bound-is-reached',1,'']]],
  ['common_20parameters_14',['Common Parameters',['../md_docs_2tutorial.html#common-parameters',1,'']]],
  ['common_20utility_15',['Common Utility',['../md_docs_2tutorial.html#common-utility',1,'']]],
  ['compatibilty_16',['Compiler Compatibilty',['../index.html#compiler-compatibilty',1,'']]],
  ['compiler_20compatibilty_17',['Compiler Compatibilty',['../index.html#compiler-compatibilty',1,'']]],
  ['complete_20example_18',['Complete Example',['../md_docs_2tutorial.html#complete-example',1,'']]],
  ['compound_20arguments_19',['Compound Arguments',['../md_docs_2tutorial.html#compound-arguments',1,'']]],
  ['concepts_2ehpp_20',['concepts.hpp',['../util_2concepts_8hpp.html',1,'(Global Namespace)'],['../action_2util_2concepts_8hpp.html',1,'(Global Namespace)']]],
  ['consume_20all_20command_20line_20values_20until_20it_20s_20upper_20nargs_20bound_20is_20reached_21',['6. &lt;tt&gt;greedy&lt;/tt&gt; - If this option is set, the argument will consume ALL command-line values until it&apos;s upper nargs bound is reached.',['../md_docs_2tutorial.html#autotoc_md6-greedy---if-this-option-is-set-the-argument-will-consume-all-command-line-values-until-its-upper-nargs-bound-is-reached',1,'']]],
  ['consume_20free_20values_22',['3. Positional arguments consume free values',['../md_docs_2tutorial.html#autotoc_md3-positional-arguments-consume-free-values',1,'']]],
  ['contains_5fwhitespaces_23',['contains_whitespaces',['../namespaceap_1_1util.html#a48bda5bed5591c247fa530e7a8d04947',1,'ap::util']]],
  ['convertible_24',['convertible',['../group__util.html#gga34f903792191e4dfd4b5749153f50fbaae0a23947029316880c29e8533d8662a3',1,'ap::util']]],
  ['count_25',['count',['../classap_1_1argument.html#aa62c74618fbed6450a50fa83ae48e7a5',1,'ap::argument::count()'],['../classap_1_1argument__parser.html#ae42161f9323643d6b6e63d361f974325',1,'ap::argument_parser::count()'],['../classap_1_1detail_1_1argument__base.html#a43fff665c9ed0098adf83cb6b3074b75',1,'ap::detail::argument_base::count()']]],
  ['count_5ftype_26',['count_type',['../namespaceap_1_1nargs.html#ac76e699bbd08ac059614baede9203a54',1,'ap::nargs::count_type'],['../classap_1_1argument.html#a6d81e9e08f3a2d69312eb371448bd397',1,'ap::argument::count_type']]],
  ['cpp_20ap_27',['cpp ap',['../index.html',1,'CPP-AP'],['../md_docs_2tutorial.html#setting-up-cpp-ap',1,'Setting Up CPP-AP']]],
  ['create_28',['create',['../classap_1_1argument__group.html#a91780f8f6a88935306ccbbcfb31098f2',1,'ap::argument_group']]],
  ['creating_20new_20groups_29',['Creating New Groups',['../md_docs_2tutorial.html#creating-new-groups',1,'']]],
  ['creating_20subparsers_30',['Creating Subparsers',['../md_docs_2tutorial.html#creating-subparsers',1,'']]],
  ['curr_5farg_31',['curr_arg',['../structap_1_1argument__parser_1_1parsing__state.html#aa3adc7134915ce4c0f4220502bd7ace9',1,'ap::argument_parser::parsing_state']]],
  ['curr_5fpos_5farg_5fit_32',['curr_pos_arg_it',['../structap_1_1argument__parser_1_1parsing__state.html#a96a2bb1f4a3f103b546ef7383d86f134',1,'ap::argument_parser::parsing_state']]]
];
