name: documentation

on:
  pull_request:
    branches:
      - '*'
  push:
    tags:
      - 'v*'

jobs:
  build-doc:
    name: Build and Validate Documentation
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: sudo apt install doxygen -y

      - name: Extract version from CMakeLists.txt
        id: extract_version
        run: |
          VERSION=$(grep -Po '(?<=project\([^)]*VERSION\s)[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Validate version with Doxyfile
        run: |
          DOXY_VERSION=$(grep -Po '(?<=PROJECT_NUMBER\s=\s).*' Doxyfile)
          if [ "$DOXY_VERSION" != "$VERSION" ]; then
            echo "❌ Version mismatch: CMakeLists.txt = $VERSION, Doxyfile = $DOXY_VERSION"
            exit 1
          fi
          echo "✅ Version match: $VERSION"

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Validate output
        run: test -d documentation && test -f documentation/index.html

  deploy-doc:
    name: Deploy Documentation
    if: github.event_name == 'push'
    needs: build-doc
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: sudo apt install doxygen -y

      - name: Extract version from CMakeLists.txt
        run: |
          VERSION=$(grep -Po '(?<=project\([^)]*VERSION\s)[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
          publish_branch: gh-pages
          destination_dir: ${{ env.VERSION }}
