name: format
on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/format.yaml
      - scripts/format.py
      - include/**
      - tests/include/**
      - tests/source/**
      - tests/app/**

jobs:
  build:
    name: Test code formatting
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Test formatting
        shell: bash
        run: |
          python3 scripts/format.py --check
