name: format
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        shell: bash
        run: |
          sudo bash ./scripts/env/install_clang_format_17.sh
        continue-on-error: false

      - name: Test formatting
        shell: bash
        run: |
          bash ./scripts/format/unix.sh --check
