name: g++
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        env:
          CC:  gcc-11
          CXX: g++-11
        run: |
          cd example
          make CXX=g++-11
        continue-on-error: false
