name: test
on:
  push:
    branches:
      - '*'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        env:
          CC:  gcc-11
          CXX: g++-11
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_C_COMPILER=gcc-11
        continue-on-error: false

      - name: Build test executable
        run: |
          cd build && make
        continue-on-error: false

      - name: Run tests
        run: |
          ./build/test/run_test
        continue-on-error: false
