var searchData=
[
  ['name_0',['name',['../classap_1_1detail_1_1argument__base.html#a76bcb06030370fc7aa4098785cd4074f',1,'ap::detail::argument_base']]],
  ['nargs_1',['nargs',['../classap_1_1argument_1_1optional.html#a9afbe48044e689c917740b9175c43c9c',1,'ap::argument::optional::nargs(const nargs::range &amp;range) noexcept'],['../classap_1_1argument_1_1optional.html#ae82d427083ea3f75ea1520a53139c27d',1,'ap::argument::optional::nargs(const count_type n) noexcept'],['../classap_1_1argument_1_1optional.html#aa9ec0a4a6e9da14fc9a7726e3bb19046',1,'ap::argument::optional::nargs(const count_type lower_bound, const count_type upper_bound) noexcept']]],
  ['nargs_20tt_20sets_20the_20allowed_20number_20of_20values_20to_20be_20parsed_20for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_2',['&lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['no_20values_20follow_3',['&lt;tt&gt;implicit_value&lt;/tt&gt; - A value which will be set for an argument if only it&apos;s flag is parsed from the command-line but no values follow.',['../md_docs_2tutorial.html#implicit_value---a-value-which-will-be-set-for-an-argument-if-only-its-flag-is-parsed-from-the-command-line-but-no-values-follow',1,'']]],
  ['no_20values_20for_20this_20argument_20are_20parsed_4',['&lt;tt&gt;default_value&lt;/tt&gt; - The default value for an argument which will be used if no values for this argument are parsed',['../md_docs_2tutorial.html#default_value---the-default-value-for-an-argument-which-will-be-used-if-no-values-for-this-argument-are-parsed',1,'']]],
  ['not_20passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_5',['&lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['notes_6',['Dev Notes',['../md_docs_2dev__notes.html',1,'']]],
  ['number_20of_20values_20to_20be_20parsed_20for_20an_20argument_20this_20can_20be_20set_20as_20a_3a_7',['&lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument. This can be set as a:',['../md_docs_2tutorial.html#nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument-this-can-be-set-as-a',1,'']]],
  ['nvalues_5fordering_8',['nvalues_ordering',['../classap_1_1detail_1_1argument__base.html#a20479ca0a1a18ca3c1fc6ee54ce8352e',1,'ap::detail::argument_base']]]
];
