var searchData=
[
  ['p_5finput_0',['p_input',['../namespaceargon.html#a958295d6fc5c8ff8b1da658b1dde6778a918ad2ff30cfa8b5018b0479aadef7cd',1,'argon']]],
  ['p_5foutput_1',['p_output',['../namespaceargon.html#a958295d6fc5c8ff8b1da658b1dde6778a08173b515fb5e9d04aaa45529dad7c24',1,'argon']]],
  ['pages_2',['Related Pages',['../index.html#related-pages',1,'']]],
  ['parameter_20values_3',['Predefined Parameter Values',['../md_docs_2tutorial.html#predefined-parameter-values',1,'']]],
  ['parameter_5fdescriptor_4',['parameter_descriptor',['../structargon_1_1detail_1_1parameter__descriptor.html',1,'argon::detail']]],
  ['parameters_5',['parameters',['../md_docs_2tutorial.html#argument-parameters',1,'Argument Parameters'],['../md_docs_2tutorial.html#common-parameters',1,'Common Parameters']]],
  ['parameters_20specific_20for_20optional_20arguments_6',['Parameters Specific for Optional Arguments',['../md_docs_2tutorial.html#parameters-specific-for-optional-arguments',1,'']]],
  ['params_7',['params',['../classargon_1_1detail_1_1help__builder.html#a9c4fc344746db41fe2b9949b528e0151',1,'argon::detail::help_builder']]],
  ['parse_5fargs_8',['parse_args',['../classargon_1_1argument__parser.html#a43e99f316aaab1f09b6b6d67422d4718',1,'argon::argument_parser::parse_args(int argc, char *argv[])'],['../classargon_1_1argument__parser.html#a48d2bc3804047720c08f7276d6f144a3',1,'argon::argument_parser::parse_args(const AR &amp;argv_rng)']]],
  ['parse_5fknown_5fargs_9',['parse_known_args',['../classargon_1_1argument__parser.html#a4a22f3561a191902a1571ebf2b21f595',1,'argon::argument_parser::parse_known_args(int argc, char *argv[])'],['../classargon_1_1argument__parser.html#aec38284a9bd9a8ca71531b98f4b682f6',1,'argon::argument_parser::parse_known_args(const AR &amp;argv_rng)']]],
  ['parse_5fknown_5fonly_10',['parse_known_only',['../structargon_1_1argument__parser_1_1parsing__state.html#aaf95c3aeab4460100b924035b770fd7b',1,'argon::argument_parser::parsing_state']]],
  ['parsed_11',['9. &lt;tt&gt;default_values&lt;/tt&gt; - A list of values which will be used if no values for an argument have been parsed',['../md_docs_2tutorial.html#autotoc_md9-default_values---a-list-of-values-which-will-be-used-if-no-values-for-an-argument-have-been-parsed',1,'']]],
  ['parsed_20for_20an_20argument_12',['5. &lt;tt&gt;nargs&lt;/tt&gt; - Sets the allowed number of values to be parsed for an argument.',['../md_docs_2tutorial.html#autotoc_md5-nargs---sets-the-allowed-number-of-values-to-be-parsed-for-an-argument',1,'']]],
  ['parsed_20from_20the_20command_20line_13',['2. &lt;tt&gt;implicit_values&lt;/tt&gt; - A list of values which will be set for an argument if only its flag but no values are parsed from the command-line.',['../md_docs_2tutorial.html#autotoc_md2-implicit_values---a-list-of-values-which-will-be-set-for-an-argument-if-only-its-flag-but-no-values-are-parsed-from-the-command-line',1,'']]],
  ['parsed_20in_20the_20order_20of_20definition_14',['2. Positional arguments are parsed in the order of definition',['../md_docs_2tutorial.html#autotoc_md2-positional-arguments-are-parsed-in-the-order-of-definition',1,'']]],
  ['parsed_20only_20with_20a_20flag_15',['1. Optional arguments are parsed only with a flag',['../md_docs_2tutorial.html#autotoc_md1-optional-arguments-are-parsed-only-with-a-flag',1,'']]],
  ['parser_20class_16',['The Parser Class',['../md_docs_2tutorial.html#the-parser-class',1,'']]],
  ['parser_20class_20instance_17',['1. &lt;tt&gt;help&lt;/tt&gt; - The argument&apos;s description which will be printed when printing the parser class instance.',['../md_docs_2tutorial.html#autotoc_md1-help---the-arguments-description-which-will-be-printed-when-printing-the-parser-class-instance',1,'']]],
  ['parser_20state_18',['Tracking Parser State',['../md_docs_2tutorial.html#tracking-parser-state',1,'']]],
  ['parsing_20an_20argument_20s_20flag_19',['1. on-flag actions - Functions that are called immediately after parsing an argument&apos;s flag.',['../md_docs_2tutorial.html#autotoc_md1-on-flag-actions---functions-that-are-called-immediately-after-parsing-an-arguments-flag',1,'']]],
  ['parsing_20an_20argument_20s_20value_20',['8. value actions - Functions that are called after parsing an argument&apos;s value.',['../md_docs_2tutorial.html#autotoc_md8-value-actions---functions-that-are-called-after-parsing-an-arguments-value',1,'']]],
  ['parsing_20arguments_21',['Parsing Arguments',['../md_docs_2tutorial.html#parsing-arguments',1,'']]],
  ['parsing_20arguments_20with_20subparsers_22',['Parsing Arguments with Subparsers',['../md_docs_2tutorial.html#parsing-arguments-with-subparsers',1,'']]],
  ['parsing_20known_20arguments_23',['Parsing Known Arguments',['../md_docs_2tutorial.html#parsing-known-arguments',1,'']]],
  ['parsing_20rules_24',['Basic Argument Parsing Rules',['../md_docs_2tutorial.html#basic-argument-parsing-rules',1,'']]],
  ['parsing_20states_25',['Example: Inspecting Parsing States',['../md_docs_2tutorial.html#example-inspecting-parsing-states',1,'']]],
  ['parsing_5ffailure_26',['parsing_failure',['../structargon_1_1parsing__failure.html',1,'argon::parsing_failure'],['../structargon_1_1parsing__failure.html#a34573ae7a91d667b26feaa5f76c33bef',1,'argon::parsing_failure::parsing_failure()']]],
  ['parsing_5fstate_27',['parsing_state',['../structargon_1_1argument__parser_1_1parsing__state.html',1,'argon::argument_parser::parsing_state'],['../structargon_1_1argument__parser_1_1parsing__state.html#a85e55e0c78de2025eea92ee9b145b762',1,'argon::argument_parser::parsing_state::parsing_state()']]],
  ['passed_20in_20the_20command_20line_20an_20exception_20will_20be_20thrown_28',['3. &lt;tt&gt;required&lt;/tt&gt; - If this option is set for an argument and it&apos;s value is not passed in the command-line, an exception will be thrown.',['../md_docs_2tutorial.html#autotoc_md3-required---if-this-option-is-set-for-an-argument-and-its-value-is-not-passed-in-the-command-line-an-exception-will-be-thrown',1,'']]],
  ['patch_29',['patch',['../structargon_1_1version.html#a7d183d36286456c2ee4bed6bf707dd3a',1,'argon::version']]],
  ['positional_30',['positional',['../namespaceargon.html#a4b32eb6291a15bebf85d8ebbd3147845ae2d45ea19c2efd31814277330dcdb556',1,'argon']]],
  ['positional_20arguments_20are_20parsed_20in_20the_20order_20of_20definition_31',['2. Positional arguments are parsed in the order of definition',['../md_docs_2tutorial.html#autotoc_md2-positional-arguments-are-parsed-in-the-order-of-definition',1,'']]],
  ['positional_20arguments_20consume_20free_20values_32',['3. Positional arguments consume free values',['../md_docs_2tutorial.html#autotoc_md3-positional-arguments-consume-free-values',1,'']]],
  ['positional_5fargument_33',['positional_argument',['../namespaceargon.html#a85d6286f8478bab68a60b8d1b94a792a',1,'argon']]],
  ['positional_5fspecific_5ftype_34',['positional_specific_type',['../classargon_1_1argument.html#a2e88861767ec67ec0c976857873c19da',1,'argon::argument']]],
  ['predefined_20parameter_20values_35',['Predefined Parameter Values',['../md_docs_2tutorial.html#predefined-parameter-values',1,'']]],
  ['predefined_2ehpp_36',['predefined.hpp',['../predefined_8hpp.html',1,'']]],
  ['prerequisites_37',['Prerequisites',['../md_docs_2dev__notes.html#prerequisites',1,'']]],
  ['primary_38',['primary',['../structargon_1_1detail_1_1argument__name.html#af71cfec6f1e3bf35f580bee8e8745b71',1,'argon::detail::argument_name']]],
  ['print_5fhelp_39',['print_help',['../classargon_1_1argument__parser.html#a033d6fcc07b8f7f83240d8184fada3ec',1,'argon::argument_parser::print_help()'],['../namespaceargon_1_1action.html#a44ea15f3783549970dfb073ee1a1a950',1,'argon::action::print_help()']]],
  ['print_5fversion_40',['print_version',['../classargon_1_1argument__parser.html#a04d31e913201a29a5b7586c2bfdab75d',1,'argon::argument_parser']]],
  ['printed_20when_20printing_20the_20parser_20class_20instance_41',['1. &lt;tt&gt;help&lt;/tt&gt; - The argument&apos;s description which will be printed when printing the parser class instance.',['../md_docs_2tutorial.html#autotoc_md1-help---the-arguments-description-which-will-be-printed-when-printing-the-parser-class-instance',1,'']]],
  ['printing_20the_20parser_20class_20instance_42',['1. &lt;tt&gt;help&lt;/tt&gt; - The argument&apos;s description which will be printed when printing the parser class instance.',['../md_docs_2tutorial.html#autotoc_md1-help---the-arguments-description-which-will-be-printed-when-printing-the-parser-class-instance',1,'']]],
  ['program_20description_43',['2. &lt;tt&gt;hidden&lt;/tt&gt; - If this option is set for an argument, then it will not be included in the program description.',['../md_docs_2tutorial.html#autotoc_md2-hidden---if-this-option-is-set-for-an-argument-then-it-will-not-be-included-in-the-program-description',1,'']]],
  ['program_5fdescription_44',['program_description',['../classargon_1_1argument__parser.html#a39a8e3baa428eab82f4f54390a08d511',1,'argon::argument_parser']]],
  ['program_5fname_45',['program_name',['../classargon_1_1argument__parser.html#a15b0451cd93525bfd6bc66db4446f8c0',1,'argon::argument_parser']]],
  ['program_5fversion_46',['program_version',['../classargon_1_1argument__parser.html#aae6754b1534a9f94e267651c24768e11',1,'argon::argument_parser::program_version(const version &amp;version) noexcept'],['../classargon_1_1argument__parser.html#aeac3047ad5f3fc34c999db6cae268306',1,'argon::argument_parser::program_version(std::string_view version)']]]
];
